name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd app
        npm install --force
    
    - name: Generate Prisma Client
      run: |
        cd app
        npx prisma generate
    
    - name: Build application
      run: |
        cd app
        npm run build
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd ~/devops_app
          git pull origin main
          cd app
          npm install --force
          npx prisma generate
          npm run build
          docker rm -f devops-app
          docker run -d --name devops-app -p 3000:3000 -v $(pwd):/app -w /app node:18-alpine sh -c "npm run start"
          echo "Deploy realizado com sucesso!"
