name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd app
        npm install --force
    
    - name: Fix Prisma schema
      run: |
        cd app
        sed -i '/output = /d' prisma/schema.prisma
        sed -i 's/provider = "postgresql"/provider = "sqlite"/' prisma/schema.prisma
        sed -i 's/url.*= env("DATABASE_URL")/url = "file:..\/build.db"/' prisma/schema.prisma
    
    - name: Generate Prisma Client
      run: |
        cd app
        npx prisma generate
    
    - name: Create build database
      run: |
        cd app
        npx prisma db push
    
    - name: Build application
      run: |
        cd app
        npm run build
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd ~/devops_app
          git pull origin main
          cd app
          npm install --force
          sed -i '/output = /d' prisma/schema.prisma
          npx prisma generate
          docker rm -f devops-app || true
          docker run -d --name devops-app -p 3000:3000 -v $(pwd):/app -w /app node:18-alpine sh -c "npm install --force && npm run dev -- --hostname 0.0.0.0"
          echo "Deploy realizado com sucesso!"
